'\" t
.\"     Title: pam_panic_pw
.\"    Author: [see the "AUTHORS" section]
.\"      Date: 2018-05-31
.\"    Manual: PAM Panic Manual
.\"    Source: PAM Panic Manual
.\"  Language: Japanese
.\"
.TH "PAM_PANIC_PW" "8" "2018-05-31" "PAM Panic マニュアル" "PAM Panic マニュアル"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH "名前"
pam_panic_pw \- \fBpam_panic\fR(8) PAM モジュールで使用するパスワードの設定と変更を行う


.SH "概要"
.HP \w'\fBpam_panic_pw\fR\ 'u
\fBpam_panic_pw\fR


.SH "説明"
.PP
\fBpam_panic_pw\fR は \fBpam_panic\fR(8) PAM モジュールで使用するパスワードの設定および変更を行います。
.PP
認証パスワードとパニックパスワードの2つのパスワードを用意します。
認証パスワードは、通常の認証に使用します。
パニックパスワードは、パニック機能の発動に使用します。


.SH "返り値"
.PP
0
.RS 4
パスワードは正しく設定されました。
.RE
.PP
1
.RS 4
アクセスが拒否されました。
.RE
.PP
2
.RS 4
パスワードファイルを開けません。
.RE


.SH "ファイル"
.PP
__PAMPANICPW__
.RS 4
パスワードの設定および変更を行うためのプログラムです。
.RE
.PP
__PPASSFILE__
.RS 4
パスワードファイルです。
.RE


.SH "バグ報告"
.PP
<https://github\&.com/pampanic/pam_panic> で、バグの報告やプルリクエストを行ってください。


.SH "関連項目"
.PP
\fBpam_panic\fR(8),
\fBcryptsetup\fR(8),
\fBpam\&.conf\fR(5),
\fBpam\fR(8)\&.


.SH "著者"

.PD 0
.PP
pam_panic は Bandie <bandie@chaospott\&.de> によって作成されました。
.PP
この翻訳は Chromium Neptune <chromium@neplanet\&.com> によって作成されています。
