'\" t
.\"     Title: pam_panic
.\"    Author: [see the "AUTHORS" section]
.\"      Date: 2018-05-31
.\"    Manual: Linux-PAM Panic Manual
.\"    Source: Linux-PAM Panic Manual
.\"  Language: Japanese
.\"
.TH "PAM_PANIC" "8" "2018-05-31" "PAM Panic マニュアル" "PAM Panic マニュアル"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------


.SH "名前"
pam_panic \- 緊急時に機密データを保護するPAMモジュール


.SH "概要"
.HP \w'\fBpam_panic.so\fR\ 'u
\fBpam_panic.so\fR [password] [allow=\fIUUID(GPT)\fR] [reject=\fIUUID(GPT)\fR] [reboot] [poweroff] [serious=\fIUUID\fR]


.SH "説明"
.PP
pam_panic PAMモジュールは、緊急時にデータを保護するためのパニック機能を実装します。
.PP
このPAMモジュールを使用するには、次の2つの方法があります。
.PD 0
.PP
方法1:
.RS 2
認証キーとパニックキーの2つのデバイスをキーとして使用します。
認証キーではパスワード認証をスキップし、パニックキーではパニック機能が起動します。
.RE
方法2:
.RS 2
パスワードを2つ用意します。認証パスワードとパニックパスワードです。認証パスワードでは通常通り認証が行われ、パニックパスワードではパニック機能が起動します。
.RE

.PD 1
.PP
パニック機能:
.RS 2
この機能の動作は次の引数によって指定されます: \fBreboot\fR, \fBpoweroff\fR または \fBserious\fR\ 。詳細については、 \fBOPTIONS\fR セクションを確認してください。
.RE


.SH "オプション"
.PP
\fBpassword\fR
.RS 4
パスワードを認証に使用します。
引数に \fBallow\fR と \fBreject\fR が指定されている場合、このオプションは無視されます。
.PD 0
.PP
パスワードは \fBpam_panic_pw\fR(1) コマンドによって指定できます。
.RE
.PD 1
.PP

\fBallow=\fR\fB\fIUUID(GPT)\fR\fR
.RS 4
デバイスのUUIDを認証に使用します。
.PD 0
.PP
.PD 1
デバイスはGPTでフォーマットされている必要があり、最低1つのパーティションを含んでいる必要があります。
GPTでフォーマットされたデバイスのUUIDは次のようになります: "12345678-9ABC-DEF0-1234-56789ABCDEF0"。
.PP
詳細については \fBUUIDを調べる方法\fR を確認してください。
.RE
.PP

\fBreject=\fR\fB\fIUUID(GPT)\fR\fR
.RS 4
緊急時に使用するデバイスのUUIDを指定します。このデバイスが存在する場合、\fBreboot\fR, \fBpoweroff\fR またはパニック機能が発動します。 パニック機能は \fBreboot\fR, \fBpoweroff\fR, \fBserious\fR のうち、いずれか1つ以上で指定されます。
.PD 0
.PP
.PD 1
デバイスはGPTでフォーマットされている必要があり、最低1つのパーティションを含んでいる必要があります。
GPTでフォーマットされたデバイスのUUIDは次のようになります: "12345678-9ABC-DEF0-1234-56789ABCDEF0"。
.PP
詳細については \fBUUIDを調べる方法\fR を確認してください。
.RE
.PP

\fBreboot\fR (推奨)
.RS 4
\fBreject\fR で指定されたデバイスが検知された場合、再起動します。
.PP
\fBpoweroff\fR が同時に指定されている場合、 \fBreboot\fR は無視されます。
.RE
.PP

\fBpoweroff\fR
.RS 4
\fBreject\fR で指定されたデバイスが検知された場合、シャットダウンします。
セキュリティ上の理由から、このオプションは推奨されません。
.RE
.PP

\fBserious=\fR\fB\fIUUID\fR\fR
.RS 4
LUKSヘッダーを消去するための鍵となるデバイスのUUIDを指定します。
LUKSヘッダーを消去した場合、データは復元できなくなります。
.PP
注意: この機能を使用する前に、LUKSヘッダーをバックアップしておくことをおすすめします。
.RE
.PP


.SH "USAGE"
.PP
モジュールを使用するためには、PAMを設定する必要があります。詳細については、 \fBpam.conf(5)\fR を参照してください。
.PP
多くの場合、PAM設定ファイルの先頭に次の内容を設定すればよいでしょう。
.PD 0
.RS 4
auth       requisite    __PAMPANICSO__ auth=<UUID> reject=<UUID> reboot serious=<UUID>
.PP
account    requisite    __PAMPANICSO__
.RE
Or: 
.RS 4
auth       requisite    __PAMPANICSO__ password reboot serious=<UUID>
.PP
account    requisite    __PAMPANICSO__
.RE
.PD 1


.SH "UUIDを調べる方法"
.PP
\fI/dev/disk/by-partuuid\fR でUUIDを調べることができます。
"\fBls -l /dev/disk/by-partuuid/\fR" を任意のシェルで実行して、どのデバイスがどのUUIDかを調べる必要があるかもしれません。

.SH "返り値"
.PP
PAM_SUCCESS
.RS 4
アクセスは許可されました。
.RE
.PP
PAM_IGNORE
.RS 4
エラーが発生しました。モジュールは無視されます。
.RE
.PP
PAM_MAXTRIES
.RS 4
リムーバブルメディアが検知されませんでした。
.RE


.SH "ファイル"
.PP
__PAMPANICSO__
.RS 4
このPAMモジュールです。
.RE
.PP
__PAMPANICPW__
.RS 4
パスワードの設定および変更を行うためのプログラムです。
.RE


.SH "バグ報告"
.PP
<https://github.com/pampanic/pam_panic> で、バグの報告やプルリクエストを行ってください。


.SH "関連項目"
.PP
\fBpam_panic_pw\fR(1),
\fBcryptsetup\fR(8),
\fBpam\fR(8),
\fBpam.conf\fR(5)


.SH "著者"
.PD 0
.PP
pam_panic は Bandie <bandie@chaospott.de> によって作成されました。
.PP
この翻訳は Chromium Neptune <chromium@neplanet.com> によって作成されています。
